// CMSC 430 Compiler Theory and Design
// Project 1 Skeleton
// UMGC CITE
// Summer 2023

// This file contains the enumerated type definition for tokens

enum Tokens {ADDOP = 256, MULOP, REMOP, EXPOP, NEGOP, ANDOP, RELOP, OROP, NOTOP, ARROW, BEGIN_, CASE, CHARACTER, END,
     ENDSWITCH, FUNCTION, INTEGER, IS, LIST, OF, OTHERS, RETURNS, SWITCH, WHEN, ELSE, ELSEIF, ENDFOLD, ENDIF, FOLD, IF,
    LEFT, REAL, RIGHT, THEN,IDENTIFIER, HEX_LITERAL, INT_LITERAL, CHAR_LITERAL, REAL_LITERAL};
